### ISSUE TITLE
Environment variable USERNAME causes errors

### ISSUE THREAD

**Issue by GameGodS3** [aldrinjenson/moodle-automation#2]
First of all, really love your project. Thank you for this lifesaver :smile: 

There's just a small improvement I'd like to put across. 
In `.env` you have an environment variable called `USERNAME`. Occasionally this causes problems in Linux (as of mine, Manjaro Linux) and so does for Heroku. What happens is, the app tries to login using the system username instead of the provided username and fails to login.

As a solution, I propose to change the variable name as `MOODUSER` in .env and in the corresponding spot in `script.js` as well.

Also, for the Procfile, I had to change to `npm start` instead of `node app.js` for things to run correctly. 

Hope you verify this and adjust accordingly. 

Once more, thank you for this awesome project :smile: . 
Cheers

**Comment by aldrinjenson** [comment]
Hi, 
Thanks a lot for your kind words. 
The project was initially written in a rush and I didn't expect others to start using the project, hence there would've been some minor bugs or edge cases which I haven't considered. 🙂 
Thank you for letting me know about the env var confilct. I use Linux as well, but this worked fine on my system as I didn't have a USERNAME variable exported. I've now changed the `USERNAME` variable to `MOODLE_USERNAME ` to avoid conflicts.
I've also modified the Procfile similar to your suggestion.

I'm closing this issues in the hope that these changes should hopefully resolve the problems you mentioned(without introducing any new bugs 🙈🤞).  Feel free to open up the issue again or create a new one if necessary. 

Once again, thanks you for your kind words.
